# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3969be395f428f055cfee5f45d2cdd6734203b1dfcf72961505aadbd21ddf30d4de0c421e9f21c78f68ff3a05fc9b20ba06c4278380431bd794120c011d9d6be

test:
  secret_key_base: 17c507f379276f19cd5016fe7b665b472b69dbc0c3bf2bc02330e6a8033a93cfca19d5b4c4c183bd4a7a830f2e26868e4acfdb651004375dd51cd55432452934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
